"""make country name not unique

Revision ID: 0f4df20e5ad8
Revises: 3e8debeb5a9c
Create Date: 2025-11-06 12:00:17.324143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4df20e5ad8'
down_revision: Union[str, Sequence[str], None] = '3e8debeb5a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('countries_country_name_key'), 'countries', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('countries_country_name_key'), 'countries', ['country_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
