"""remove distributors

Revision ID: 5701b657b23c
Revises: 0f4df20e5ad8
Create Date: 2025-11-06 12:29:50.589169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5701b657b23c'
down_revision: Union[str, Sequence[str], None] = '0f4df20e5ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop movie_distributors first because it has a foreign key to distributors
    op.drop_table('movie_distributors')
    op.drop_table('distributors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_distributors',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distributor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('movie_distributors_distributor_id_fkey')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('movie_distributors_movie_id_fkey')),
    sa.PrimaryKeyConstraint('movie_id', 'distributor_id', name=op.f('movie_distributors_pkey'))
    )
    op.create_table('distributors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('distributor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('distributors_pkey')),
    sa.UniqueConstraint('distributor_name', name=op.f('distributors_distributor_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
