"""add_rating_column_to_movies

Revision ID: 74f3f25aaaa7
Revises: e79e3687afb9
Create Date: 2026-01-03 22:55:38.459411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f3f25aaaa7'
down_revision: Union[str, Sequence[str], None] = 'e79e3687afb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###
