"""Add new columns to movies

Revision ID: 7fb9d72b7194
Revises: 
Create Date: 2025-10-13 21:58:14.870541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb9d72b7194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso_3166_1', sa.String(length=2), nullable=False))
    op.create_unique_constraint(None, 'countries', ['iso_3166_1'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'iso_3166_1')
    # ### end Alembic commands ###
